# Generated by Django 6.0.1 on 2026-01-08 16:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('colegio', models.CharField(max_length=100)),
                ('dir_colegio', models.CharField(max_length=100)),
                ('origen', models.CharField(choices=[('FACEBOOK', 'Facebook Ads'), ('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('WEB', 'Pagina Web'), ('REFERIDO', 'Referido')], default='WEB', max_length=20)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('CONTACTADO', 'Contactado'), ('INTERESADO', 'Interesado'), ('POSTULANTE', 'En Proceso de Admisión'), ('MATRICULADO', 'Matriculado'), ('PERDIDO', 'Perdido/No Interesado')], default='NUEVO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('carrera_interes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspirantes', to='leads.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LLAMADA', 'Llamada Telefónica'), ('WHATSAPP', 'Mensaje de WhatsApp'), ('EMAIL', 'Correo Electrónico'), ('REUNION', 'Reunión Presencial')], max_length=20)),
                ('notas', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.CharField(max_length=100)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='leads.lead')),
            ],
        ),
    ]
